[project]
name = "zugzwang"
readme = "README.md"
dynamic = ["version"]
authors = [
    { name = "Kilian Calefice" },
]
requires-python = "==3.13"
dependencies = [
    "torch==2.11.0",
    "python-chess==1.999",
]

[project.optional-dependencies]
# install with `pip install ".[train]"`
train = [
  "tqdm==4.67.3",
]
# install with `pip install ".[inference]"`
inference = [
  "uvicorn[standard]==0.46.0",
  "fastapi==0.136.1",
]
# install with `pip install ".[dev]"`
dev = [
  "black==26.3.1",
  "isort==8.0.1",
  "pylint==4.0.5",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"
name = "pytorch-cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[project.urls]
"Repository" = "https://github.com/creed-braton/zugzwang"
"Issues" = "https://github.com/creed-braton/zugzwang/issues"
